### ISSUE TITLE
Get info from user with SecurityPrincipal in services

### ISSUE THREAD

**Issue by ricardoasc** [SaiUpadhyayula/spring-boot-microservices#10]
### Obtain user information in the request that arrives at the services

How would be a correct way to get user data just using SecurityPrincipal in my controls when a request is sent to some service?

The way the services are not exposed, to request a service you have to go through the API Gateway, which is where authorization is required.

How do I transit the authenticated user's information in Keycloak by passing the authenticated user's information to my services?

**Because in some records I will need, for example, the user ID you requested, how can I do that?**

**Comment by gianluca1606** [comment]
There should be multiple ways to achieve what you want.

I think the simplest  but also relatively secure way would be to grab the data you need at the gateway and create a jwt out of it and sign it. 

There are several code snippets for retrieving user data from spring security, i am not completely sure if spring oauth2 with spring security changes anything about it, but i think it should not. 

Then you can repass it to the other services as some Header in the requests. 
There you can retrieve the token, decode it and use this data.

**Comment by gianluca1606** [comment]
[Ther](https://cloud.spring.io/spring-cloud-static/Greenwich.RELEASE/multi/multi__more_detail.html)

This should be the answer for what you are looking. So basically you would implement the authentication on the other services also, and you can relay the token.

**Comment by SaiUpadhyayula** [comment]
As suggested by @gianluca1606 you have to use TokenRelay, to forward the request from the API Gateway to the services.

Here is the updated documentation for Token Relay - https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/#the-tokenrelay-gatewayfilter-factory
